AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  typmaquillaje:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://typmaquillaje/1e547278f88e350ccda12c5ba0c8d034
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:sa-east-1:654654320152:log-group:/aws/lambda/typmaquillaje:*
            - Effect: Allow
              Action: 
                - lambda:InvokeFunction
              Resource: "*"
        - RuntimeManagementConfig:
            AutoPublishAlias: live
      SnapStart:
        ApplyOn: None
    Metadata:
      SamResourceId: typmaquillaje
