version = 0.1
[default.deploy.parameters]
stack_name = "maquillaje-app"
resolve_s3 = true
s3_prefix = "maquillaje-app"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
